# stages:
#   - test

# hello-job:
#   stage: test
#   tags:
#     - ai-cicd-demo
#   script:
#     - echo "Runner is working"


stages:
  - pr_agent
default:
  tags:
  # - runner-gpu87
  - ai-cicd-demo
pr_agent_job:
  stage: pr_agent
  image:
    name: codingassistant/pr_agent:latest
    entrypoint: [""]
  script:
    - cd /app
    - echo "Running PR Agent action step"
    - export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"
    - echo "MR_URL=$MR_URL"
    - export gitlab__url=$CI_SERVER_URL
    - export vnpt_scm__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
    - export config__git_provider="vnpt_scm"
    - export ic_code__key=$IC_CODE_API_KEY
    - export ic_code__base_url=$IC_CODE_BASE_URL
    - python3 -m pr_agent.cli --pr_url="$MR_URL" describe
    - python3 -m pr_agent.cli --pr_url="$MR_URL" review
    - python3 -m pr_agent.cli --pr_url="$MR_URL" improve
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

